import { RouteInfo } from "./sidebar.metadata";
export const ROUTES: RouteInfo[] = [
  {
    path: "./dashboard",
    title: "dashboard",
    moduleName: "dashboard",
    iconType: "feather",
    icon: "airplay",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ADMIN"],
    submenu: [
      // {
      //   path: "/onboarding/farmers/container",
      //   title: "farmers",
      //   moduleName: "onboarding",
      //   iconType: "feather",
      //   icon: "cloud-drizzle",
      //   class: "ml-menu",
      //   groupTitle: false,
      //   badge: "",
      //   badgeClass: "",
      //   role: [""],
      //   submenu: [],
      // },

      // {
      //   path: "/onboarding/agrodealers/container",
      //   title: "agrodealers",
      //   moduleName: "onboarding",
      //   iconType: "",
      //   icon: "",
      //   class: "ml-menu",
      //   groupTitle: false,
      //   badge: "",
      //   badgeClass: "",
      //   role: [""],
      //   submenu: [],
      // },
      // {
      //   path: "/onboarding/transporters/container",
      //   title: "transporters",
      //   moduleName: "onboarding",
      //   iconType: "",
      //   icon: "",
      //   class: "ml-menu",
      //   groupTitle: false,
      //   badge: "",
      //   badgeClass: "",
      //   role: [""],
      //   submenu: [],
      // },
      // {
      //   path: "/onboarding/warehouse/container",
      //   title: "warehouse",
      //   moduleName: "onboarding",
      //   iconType: "",
      //   icon: "",
      //   class: "ml-menu",
      //   groupTitle: false,
      //   badge: "",
      //   badgeClass: "",
      //   role: [""],
      //   submenu: [],
      // },
      // {
      //   path: "/onboarding/organisation/container",
      //   title: "organisation",
      //   moduleName: "onboarding",
      //   iconType: "",
      //   icon: "",
      //   class: "ml-menu",
      //   groupTitle: false,
      //   badge: "",
      //   badgeClass: "",
      //   role: [""],
      //   submenu: [],
      // },
    ],
  },
 
  {
    path: "./digital-training",
    title: "digital training",
    moduleName: "digital-training",
    iconType: "feather",
    icon: "pen-tool",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ADMIN"],
    submenu: [],
  },

  {
    path: "./marketplace",
    title: "Market Place",
    moduleName: "marketplace",
    iconType: "feather",
    icon: "package",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ADMIN"],
    submenu: [],
  },
  
  {
    path: "./extension-services",
    title: "Extension Services",
    moduleName: "extension-services",
    iconType: "feather",
    icon: "sun",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ADMIN"],
    submenu: [],
  },

  {
    path: "./loans",
    title: "Loans",
    moduleName: "loans",
    iconType: "feather",
    icon: "book-open",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ADMIN"],
    submenu: [],
  },
  
]
